//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5477
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleTestV8.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleTestV8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon iCacheTester {
            get {
                object obj = ResourceManager.GetObject("iCacheTester", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 S01400006943616368655465737465722E737265635C
        ///S315500000009DE3BF984000027A21140005400002B1DA
        ///S3155000001001000000400003500100000011140006CA
        ///S31550000020400001A1901222184000019F901421B067
        ///S315500000304000049201000000808A20FF12800004D4
        ///S315500000401114000540000198901221B84000019605
        ///S31550000050901421B01108003C90122010D2020000DA
        ///S3155000006080A260001680001B1114000611080009BA
        ///S315500000709212202CD0024000808A200802BFFFFE38
        ///S31550000080010000001308001392126020D0124000A5
        ///S31550000090900A3FFED0324000152000 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string iCacheTester1 {
            get {
                return ResourceManager.GetString("iCacheTester1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ModuleTest {
            get {
                object obj = ResourceManager.GetObject("ModuleTest", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 S01400006943616368655465737465722E737265635C
        ///S315500000009DE3BF984000027A21140005400002B1DA
        ///S3155000001001000000400003500100000011140006CA
        ///S31550000020400001A1901222184000019F901421B067
        ///S315500000304000049201000000808A20FF12800004D4
        ///S315500000401114000540000198901221B84000019605
        ///S31550000050901421B01108003C90122010D2020000DA
        ///S3155000006080A260001680001B1114000611080009BA
        ///S315500000709212202CD0024000808A200802BFFFFE38
        ///S31550000080010000001308001392126020D0124000A5
        ///S31550000090900A3FFED0324000152000 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string NavSparkIoTester {
            get {
                return ResourceManager.GetString("NavSparkIoTester", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ResetTester {
            get {
                object obj = ResourceManager.GetObject("ResetTester", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
